# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(default='', max_length=256, verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
