# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
    ]
